import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "Who's feeling lonely in Europe?",
  "subtitle": "Around 13% of respondents in the EU reported feeling lonely most or all of the time over the previous four weeks in 2022, with the highest levels observed in Ireland and the lowest levels in the Netherlands, Czechia, Croatia and Austria.",
  "colourSchemeClasses": 7,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,0.095,false,9.5% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nBelgium,BE,0.133,false,13.3% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nBulgaria,BG,0.156,false,15.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nCroatia,HR,0.097,false,9.7% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nCyprus,CY,0.157,false,15.7% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nCzechia,CZ,0.098,false,9.8% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nDenmark,DK,0.125,false,12.5% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nEstonia,EE,0.136,false,13.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nFinland,FI,0.118,false,11.8% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nFrance,FR,0.149,false,14.9% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nGermany,DE,0.122,false,12.2% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nGreece,EL,0.161,false,16.1% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nHungary,HU,0.126,false,12.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nIreland,IE,0.190,false,19.0% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nItaly,IT,0.132,false,13.2% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nLatvia,LV,0.111,false,11.1% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nLithuania,LT,0.153,false,15.3% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nLuxembourg,LU,0.159,false,15.9% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nMalta,MT,0.136,false,13.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nNetherlands,NL,0.087,false,8.7% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nPoland,PL,0.130,false,13.0% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nPortugal,PT,0.116,false,11.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nRomania,RO,0.152,false,15.2% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nSlovakia,SK,0.116,false,11.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nSlovenia,SI,0.098,false,9.8% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nSpain,ES,0.101,false,10.1% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,\nSweden,SE,0.144,false,14.4% of respondents reported feeling lonely most or all of the time over the previous four weeks.,Source: JRC EU Loneliness Survey 2022,https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 0.095,
      "extraInfo": false,
      "text_content": "9.5% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 0.133,
      "extraInfo": false,
      "text_content": "13.3% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 0.156,
      "extraInfo": false,
      "text_content": "15.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 0.097,
      "extraInfo": false,
      "text_content": "9.7% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 0.157,
      "extraInfo": false,
      "text_content": "15.7% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 0.098,
      "extraInfo": false,
      "text_content": "9.8% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 0.125,
      "extraInfo": false,
      "text_content": "12.5% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 0.136,
      "extraInfo": false,
      "text_content": "13.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 0.118,
      "extraInfo": false,
      "text_content": "11.8% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 0.149,
      "extraInfo": false,
      "text_content": "14.9% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 0.122,
      "extraInfo": false,
      "text_content": "12.2% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 0.161,
      "extraInfo": false,
      "text_content": "16.1% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 0.126,
      "extraInfo": false,
      "text_content": "12.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 0.19,
      "extraInfo": false,
      "text_content": "19.0% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0.132,
      "extraInfo": false,
      "text_content": "13.2% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 0.111,
      "extraInfo": false,
      "text_content": "11.1% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 0.153,
      "extraInfo": false,
      "text_content": "15.3% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 0.159,
      "extraInfo": false,
      "text_content": "15.9% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 0.136,
      "extraInfo": false,
      "text_content": "13.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 0.087,
      "extraInfo": false,
      "text_content": "8.7% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 0.13,
      "extraInfo": false,
      "text_content": "13.0% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 0.116,
      "extraInfo": false,
      "text_content": "11.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 0.152,
      "extraInfo": false,
      "text_content": "15.2% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 0.116,
      "extraInfo": false,
      "text_content": "11.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 0.098,
      "extraInfo": false,
      "text_content": "9.8% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0.101,
      "extraInfo": false,
      "text_content": "10.1% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 0.144,
      "extraInfo": false,
      "text_content": "14.4% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
      "link_text": "Source: JRC EU Loneliness Survey 2022",
      "link_url_target": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "blue-purple",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "Joint Research Centre (2026)",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "This map is based on the 2022 EU Loneliness Survey conducted by the European Commission’s Joint Research Centre. The figures show the share of respondents aged 16 and over who reported feeling lonely most or all of the time during the previous four weeks.The data reflect self-reported loneliness.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://joint-research-centre.ec.europa.eu/projects-and-activities/survey-methods-and-analysis-centre/loneliness/loneliness-prevalence-eu_en",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": false,
  "customUnitLabel": "",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "Who's feeling lonely in Europe?",
    "subtitle": "Around 13% of respondents in the EU reported feeling lonely most or all of the time over the previous four weeks in 2022, with the highest levels observed in Ireland and the lowest levels in the Netherlands, Czechia, Croatia and Austria.",
    "textNoteDescription": "Note",
    "textNote": "This map is based on the 2022 EU Loneliness Survey conducted by the European Commission’s Joint Research Centre. The figures show the share of respondents aged 16 and over who reported feeling lonely most or all of the time during the previous four weeks.The data reflect self-reported loneliness.",
    "textSourceDescription": "Source",
    "textSource": "Joint Research Centre (2026)",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_AT": "9.5% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_BE": "13.3% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_BG": "15.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_HR": "9.7% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_CY": "15.7% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_CZ": "9.8% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_DK": "12.5% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_EE": "13.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_FI": "11.8% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_FR": "14.9% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_DE": "12.2% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_EL": "16.1% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_HU": "12.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_IE": "19.0% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_IT": "13.2% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_LV": "11.1% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_LT": "15.3% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_LU": "15.9% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_MT": "13.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_NL": "8.7% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_PL": "13.0% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_PT": "11.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_RO": "15.2% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_SK": "11.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_SI": "9.8% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_ES": "10.1% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
    "extraInfo_SE": "14.4% of respondents reported feeling lonely most or all of the time over the previous four weeks."
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_AT": "9.5% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_BE": "13.3% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_BG": "15.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_HR": "9.7% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_CY": "15.7% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_CZ": "9.8% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_DK": "12.5% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_EE": "13.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_FI": "11.8% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_FR": "14.9% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_DE": "12.2% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_EL": "16.1% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_HU": "12.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_IE": "19.0% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_IT": "13.2% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_LV": "11.1% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_LT": "15.3% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_LU": "15.9% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_MT": "13.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_NL": "8.7% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_PL": "13.0% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_PT": "11.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_RO": "15.2% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_SK": "11.6% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_SI": "9.8% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_ES": "10.1% of respondents reported feeling lonely most or all of the time over the previous four weeks.",
  "extraInfo_SE": "14.4% of respondents reported feeling lonely most or all of the time over the previous four weeks."
});